### ISSUE TITLE
Compiling error. Problem in including qt5 headers?

### ISSUE THREAD

**Issue by dario79** [frsfnrrg/step-gdml#1]
Hello,
I need to convert step/cad files to GDML to use with GEANT4 and found out this.
After installing opencascade I'm now trying to compile this code in Ubuntu 14.04  3.13.0-45-generic x86_64 but I'm getting errors. I don't know much about Qt coding and I don't completely understand these errors, could someone please help?
gcc version is 4.8.2, opencascade version is 6.8.0 and apparently $CASROOT and $OCCLIB are  properly set (qmake says).
When compiling I get:

make -f Makefile.Release
make[1]: ingresso nella directory "[CUT]/.local/share/Trash/files/step-gdml-master"
g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIE -DCSFDB -DQT_NO_DEPRECATED -DLIN -DLININTEL -DOCC_CONVERT_SIGNALS -DHAVE_CONFIG_H -DHAVE_WOK_CONFIG_H -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../../../../../opencascade -I../../../../../opencascade/inc -I/usr/lib/x86_64-linux-gnu/qt5/include/QtCore -I/usr/lib/x86_64-linux-gnu/qt5/include/QtGui -I/usr/lib/x86_64-linux-gnu/qt5/include -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -Ibuild/moc -o build/obj/main.o src/main.cpp
In file included from /usr/include/qt5/QtCore/qobject.h:48:0,
                 from /usr/include/qt5/QtCore/qabstractanimation.h:45,
                 from /usr/include/qt5/QtCore/QtCore:4,
                 from src/main.cpp:1:
/usr/include/qt5/QtCore/qobjectdefs.h:102:5: error: ‘QT_DEPRECATED’ does not name a type
     QT_DEPRECATED static inline QString trUtf8(const char *s, const char *c = 0, int n = -1) \
     ^
/usr/include/qt5/QtCore/qobjectdefs.h:152:5: note: in expansion of macro ‘QT_TR_FUNCTIONS’
     QT_TR_FUNCTIONS \
     ^
/usr/include/qt5/QtCore/qobject.h:116:5: note: in expansion of macro ‘Q_OBJECT’
     Q_OBJECT
     ^
/usr/include/qt5/QtCore/qobjectdefs.h:102:5: error: ‘QT_DEPRECATED’ does not name a type

[CUT] ... repeated for many times until it obviously ends with

In file included from ../../opencascade/inc/Message_Messenger.hxx:13:0,
                 from src/main.cpp:9:
../../opencascade/inc/TCollection_Sequence.lxx: In copy constructor ‘Message_SequenceOfPrinters::Message_SequenceOfPrinters(const Message_SequenceOfPrinters&)’:
../../opencascade/inc/Message_SequenceOfPrinters.hxx:110:30: warning: base class ‘class TCollection_BaseSequence’ should be explicitly initialized in the copy constructor [-Wextra]
 #define TCollection_Sequence Message_SequenceOfPrinters
                              ^
../../opencascade/inc/TCollection_Sequence.lxx:31:8: note: in expansion of macro ‘TCollection_Sequence’
 inline TCollection_Sequence::TCollection_Sequence(const TCollection_Sequence& theOther)
        ^
In file included from ../../opencascade/inc/TCollection_HExtendedString.hxx:13:0,
                 from ../../opencascade/inc/Message_Messenger.lxx:44,
                 from ../../opencascade/inc/Message_Messenger.hxx:110,
                 from src/main.cpp:9:
../../opencascade/inc/TCollection_ExtendedString.hxx: At global scope:
../../opencascade/inc/TCollection_ExtendedString.hxx:262:61: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   Standard_EXPORT  const  Standard_ExtString ToExtString()  const;
                                                             ^
In file included from ../../opencascade/inc/Message_Messenger.lxx:44:0,
                 from ../../opencascade/inc/Message_Messenger.hxx:110,
                 from src/main.cpp:9:
../../opencascade/inc/TCollection_HExtendedString.hxx:154:61: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   Standard_EXPORT  const  Standard_ExtString ToExtString()  const;
                                                             ^
src/main.cpp: In member function ‘virtual void CustomPrinter::Send(const TCollection_ExtendedString&, Message_Gravity, Standard_Boolean) const’:
src/main.cpp:26:25: warning: format not a string literal and no format arguments [-Wformat-security]
             printf(alias);
                         ^
src/main.cpp: In function ‘int main(int, char*_)’:
src/main.cpp:52:22: error: variable ‘QApplication app’ has initializer but incomplete type
     QApplication app(argc, argv);
                      ^
src/main.cpp:62:11: error: ‘class MainWindow’ has no member named ‘show’
         w.show();
           ^
make[1]: *_\* [build/obj/main.o] Errore 1

Any help would be appreciated.
Thanks,
Dario

**Comment by frsfnrrg** [comment]
Step-gdml was originally designed to work with Qt4, and was tested with OpenCASCADE 6.50 and 6.80. I recently got it to compile with Qt5 as well (see commit 83f068789d3eb3ddcb58e1fabfbd2dc1ea7122ac), but on my computer it crashes, probably because of a nonstandard configuration issue that I'll hunt down later.

Try installing the latest Qt 4 version as well and compiling with it (you may want to check `qmake -v` to determine which major version qmake uses by default). The IDE QtCreator might make it easier to build explicitly with Qt4.

(The errors come mainly from the QT_NO_DEPRECATED flag, which only seems to apply for Qt4. Also, some header files shifted. The aforementioned commit resolves those compile errors.)

**Comment by frsfnrrg** [comment]
>  but on my computer it crashes, probably because of a nonstandard configuration issue that I'll hunt down later.

Turns out it was a trivial bug. Fixed in latest commit. Qt5 should work now, albeit with slight lag.
